feature/statistics
crococoders/zhazam pull request #12
Opened 2020-05-07 15:58 UTC by Abay99

2020-05-07 16:23 UTC, alimsanzhar requested changes

2020-05-07 16:23 UTC, alimsanzhar commented on zhazam/Modules/Statistics/StatisticsViewController.swift
> +        StatisticsRowModel(totalResult: "3", measurement: "levels", resultTitle: "worst arcade result")
создавай массив в модельке, сейчас запушу свой ПР в мастер, посмотри как там сделал

2020-05-07 16:23 UTC, alimsanzhar commented on zhazam/Modules/Statistics/StatisticsViewController.swift
> +        return 1
это же не обязательно реализовывать

2020-05-07 16:23 UTC, alimsanzhar commented on zhazam/Modules/Statistics/StatisticsViewController.swift
> +            withReuseIdentifier: NSStringFromClass(StatisticsCollectionCell.self),
NSStringFromClass удали, у нас есть протокол Reusable, его заюзай

2020-05-07 16:23 UTC, alimsanzhar commented on zhazam/Modules/Statistics/StatisticsViewController.swift
> +    }
это обязательно реализовывать? по дефолту не 0?

2020-05-07 16:23 UTC, alimsanzhar commented on zhazam/Modules/Statistics/Views/StatisticsCollectionCell.swift
> +    public func configureItems(model: StatisticsRowModel) {
не создавай функцию для инициализации, заюзай свой кастомный init и все значение засеть в нем

2020-05-07 16:23 UTC, alimsanzhar commented on zhazam/Modules/Statistics/Views/StatisticsRowModel.swift
> +    let resultTitle: String?
почему они optional?

2020-05-07 16:24 UTC, alimsanzhar requested changes

2020-05-07 16:24 UTC, alimsanzhar commented on zhazam/Modules/Statistics/Views/StatisticsCollectionCell.swift
> +        self.loadFromNib()
без self

2020-05-07 16:24 UTC, alimsanzhar commented on zhazam/Modules/Statistics/StatisticsViewController.swift
> +            forCellWithReuseIdentifier: NSStringFromClass(StatisticsCollectionCell.self))
здесь тоже не нужно

2020-05-08 06:15 UTC, Abay99 commented on zhazam/Modules/Statistics/Views/StatisticsCollectionCell.swift
> +    public func configureItems(model: StatisticsRowModel) {
здесь же я передаю в UICollectionViewCell, и пришлось создать отдельную функцию

2020-05-08 06:16 UTC, Abay99 commented on zhazam/Modules/Statistics/StatisticsViewController.swift
> +        StatisticsRowModel(totalResult: "3", measurement: "levels", resultTitle: "worst arcade result")
Сделано.

2020-05-08 15:09 UTC, alimsanzhar requested changes

2020-05-08 15:09 UTC, alimsanzhar commented on zhazam/Modules/Statistics/Views/StatisticsCollectionCell.swift
> +        self.resultTitle.text = model.resultTitle
в init вынеси, зачем функцию использовать

2020-05-08 15:09 UTC, alimsanzhar commented on zhazam/Utility/Helper/Reusable.swift
> +    static var identifier: String {
зачем ты переделал его? верни обратно без statiс, просто подписываешься под этот протокол и пишешь identifier вместо StatisticsCollectionCell.identifier

2020-05-08 17:29 UTC, closed without merging