feature/onboarding add onboarding and user defaults storage
crococoders/zhazam pull request #7
Opened 2020-04-23 21:19 UTC by nurbekismagulov

2020-04-23 21:43 UTC, rymbekov commented on zhazam/Modules/Onboarding/Model/OnboardingPage.swift
> +    static let all: [OnboardingType] = [.interfaceStyle, .finish]
You can use CaseIterable protocol that automatically generates an array property of all cases in an enum

2020-04-25 15:26 UTC, alimsanzhar requested changes

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Loading/LoadingViewController.swift
> +        let viewController = OnboardingPageViewController(with: pages)
space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Loading/LoadingViewController.swift
> +}
Already used in InterfaceStyleConfigurationCommand, why do you need it here?

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/Model/OnboardingPageViewController.swift
> +    }
why are you implementing these methods if they return nil?

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/Model/OnboardingPageViewController.swift
> +
no need for space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingPageViewController.swift
> +        self.pages = pages
set pages value before super and there will be no need for making pages as var and make it optional

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/Model/OnboardingPageViewController.swift
> +        self.dataSource = self
no need for self.

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/Model/OnboardingPageViewController.swift
> +        super.viewDidLoad()
let separate super and self calls (для наглядности чтобы видеть какая часть кода является твоей реализацией)

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingPageViewController.swift
> +        self.delegate = self
remove self and move it to separate method

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingPageViewController.swift
> +        NSLayoutConstraint.activate(constraints)
Write NSLayoutConstraint.activate([...]) like sundell does, no need to instantiate a variable constants

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingPageViewController.swift
> +        guard index >= 0, index < pages.count else { return nil }
you can write it together

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingPageViewController.swift
> +        guard index > 0 else { return nil }
here too

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingViewController.swift
> +        configure()
separate

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingViewController.swift
> +            stackView.addArrangedSubview(titledTextView)
space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingViewController.swift
> +            stackView.addArrangedSubview(horizontalView)
space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingViewController.swift
> +        return true
space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Onboarding/View/OnboardingViewController.swift
> +        appDelegate.changeInterfaceStyle()
space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Views/HorizontalKeyValueView/HorizontalKeyValueView.swift
> +    var onTapBlock: (() -> Void)?
space (everywhere)

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Views/HorizontalKeyValueView/HorizontalKeyValueView.swift
> +    var onTapBlock: (() -> Void)?
can use typealias for callback, create a global one so everyone can use it

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Views/TitledTextView/TitledTextView.swift
> +    var onCompleteBlock: (() -> Void)?
let it be onComplete, without block

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Modules/Views/TitledTextView/TitledTextView.swift
> +        return true
space

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Resources/Strings/en.lproj/Localizable.strings
> +"Start" = "start";
use uppercased namings and where it needs to be lowercased call "lowercased()" method for string

2020-04-25 15:26 UTC, alimsanzhar commented on zhazam/Utility/Extensions/Optional+Extension.swift
> +}
why do we need this?

2020-05-01 10:35 UTC, nurbekismagulov commented on zhazam/Modules/Loading/LoadingViewController.swift
> +}
Different properties

2020-05-01 10:53 UTC, nurbekismagulov commented on zhazam/Utility/Extensions/Optional+Extension.swift
> +}
Used in UserDefaultsBacked for optional cases

2020-05-01 13:50 UTC, closed without merging