feature/onboarding_new
crococoders/zhazam pull request #9
Opened 2020-05-01 12:51 UTC by nurbekismagulov

2020-05-01 19:02 UTC, alimsanzhar requested changes

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingPageViewController.swift
> +    private var pages: [OnboardingPage]?
why optional? lets make it `private let pages: [OnboardingPage]`

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingPageViewController.swift
> +    private func getPage(for index: Int) -> OnboardingViewController? {
why method returns optional value?

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingViewController.swift
> +    private var page: OnboardingPage
`private let page: OnboardingPage`

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingViewController.swift
> +        configure()
name it more speicifically, configure what?

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingViewController.swift
> +                guard let `self` = self else { return }
'`self`' is an old version, now there is no need to use ``

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingViewController.swift
> +        return index
write as computed property

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Modules/Views/HorizontalKeyValueView/HorizontalKeyValueView.swift
> +final class HorizontalKeyValueView: UIView {
хуевый нейминг

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Modules/Views/TitledTextView/TitledTextView.swift
> +    private var completionString: String?
what does completionString means? make it more specifically

2020-05-01 19:02 UTC, alimsanzhar commented on zhazam/Utility/Extensions/UIView+Extension.swift
> +                                 .autoreverse, .repeat],
write array in one line

2020-05-01 20:22 UTC, nurbekismagulov commented on zhazam/Application/Configuration/Onboarding/Views/OnboardingPageViewController.swift
> +    private func getPage(for index: Int) -> OnboardingViewController? {
to avoid index out of the bounds exception

2020-05-02 08:35 UTC, alimsanzhar commented on zhazam/Modules/Views/HorizontalKeyValueView/HorizontalKeyValueView.swift
> +final class HorizontalKeyValueView: UIView {
FillTitleView

2020-05-02 08:39 UTC, alimsanzhar commented on zhazam/Modules/Views/HorizontalKeyValueView/HorizontalKeyValueView.swift
> +final class HorizontalKeyValueView: UIView {
ConfigurationView

2020-05-02 09:08 UTC, merged